INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (1, 'intégré', 'Document intégré dans l''ERP', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (2, 'comptabilisé', 'Document rentré en comptabilité', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (3, 'bon à payer', 'Document validé pour paiement', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (4, 'payé', 'Document payé', 1);

INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (101, 'lu', 'Document consulté sur le web@edi', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (102, 'imprimé', 'Document consulté dans l''objectif de l''imprimer', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (103, 'lien de téléchargement exporté', 'Les données pour construire le lien de téléchargement ont été exportées', 1);

INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (201, 'chorus_1', 'Déposée', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (203, 'chorus_3', 'Mise à disposition du destinataire', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (204, 'chorus_4', 'Rejetée par l''ordonnanceur pour erreur dans les données d''acheminement', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (205, 'chorus_5', 'Rejetée par l''ordonnanceur pour autre motif', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (206, 'chorus_6', 'Suspendue', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (207, 'chorus_7', 'Service fait', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (208, 'chorus_8', 'Mandatée / DP validée', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (209, 'chorus_9', 'Mise à disposition du comptable', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (210, 'chorus_10', 'Comptabilisée', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (211, 'chorus_11', 'Mise en paiement', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (212, 'chorus_12', 'Complétée - mise à disposition', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (213, 'chorus_13', 'Validée par le premier valideur', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (214, 'chorus_14', 'Réfusée par le premier valideur pour autre motif', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (215, 'chorus_15', 'Validation 1 hors délai', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (216, 'chorus_16', 'Validation 2 hors délai', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (217, 'chorus_17', 'Refusée par le second valideur pour autre motif', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (218, 'chorus_18', 'Validée par le second valideur', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (219, 'chorus_19', 'Refusée par la MOE pour autre motif', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (220, 'chorus_20', 'Refusée par le fournisseur pour autre motif', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (221, 'chorus_21', 'Associée', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (222, 'chorus_22', 'Conforme - non intégrée', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (223, 'chorus_23', 'Mise à disposition du premier valideur', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (224, 'chorus_24', 'Refusée par le premier valideur pour erreur dans les données d''acheminement', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (225, 'chorus_25', 'Mise à disposition du premier valideur', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (226, 'chorus_26', 'Refusée par le second valideur pour erreur des données d''acheminement', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (227, 'chorus_27', 'Mise à disposition MOE', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (228, 'chorus_28', 'Refusée par la MOE pour erreur dans les données d''acheminement', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (229, 'chorus_29', 'Prise en compte MOE', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (230, 'chorus_30', 'Mise à disposition MOA', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (231, 'chorus_31', 'Refusée par la MOA pour erreur dans les données d''acheminement', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (232, 'chorus_32', 'Refusée par la MOA pour autre motif', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (233, 'chorus_33', 'Mise à disposition fournisseur', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (234, 'chorus_34', 'Demande de complément', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (235, 'chorus_35', 'Transmise à la MOA', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (236, 'chorus_36', 'Prise en compte par le destinataire', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (237, 'chorus_37', 'Non conforme - non intégrée', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (238, 'chorus_38', 'Prise en compte par la MOA', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (239, 'chorus_39', 'Acheminée MOA', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (240, 'chorus_40', 'Acheminée MOE', 1);
INSERT INTO llx_c_atgpconnector_status (rowid, code, label, active) VALUES (241, 'chorus_41', 'Remplacé par le A22', 1);
